name: social_media_share
description: A Flutter plugin for sharing text and images
version: 0.0.4
homepage: https://github.com/viku4/Social-Media-Share.git

# publish_to: none

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.12.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.social_media_share
        pluginClass: SocialMediaSharePlugin
      # ios:
      #   pluginClass: SocialMediaSharePlugin
